export const NEW_RIDDLE_REQUESTED = 'NEW_RIDDLE_REQUESTED';
export const SET_CURRENT_RIDDLE = 'SET_CURRENT_RIDDLE';
export const SET_CORRECT_ANSWER = 'SET_CORRECT_ANSWER';
export const SET_WRONG_ANSWER = 'SET_WRONG_ANSWER';
export const SET_TIMEOUT = 'SET_TIMEOUT';
export const SET_ERROR = 'SET_ERROR';
export const RESET_GAME = 'RESET_GAME';
