name: Build on push
on:
  push:
    paths-ignore:
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        dir: "frontend"
        run: yarn install
      - name: Tests
        dir: "frontend"
        run: yarn test
      - name: Build
        dir: "frontend"
        run: yarn build
      - name: Deploy
        dir: "frontend"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=public --prod
