name: Build on push
on:
  push:
    branches:
      - master
    paths:
      - "frontend"
      - "backend"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        run: yarn install
        working-directory: frontend
      - name: Tests
        run: yarn test
        working-directory: frontend
      - name: Build
        run: yarn build
        working-directory: frontend
      - name: Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=build --prod
        working-directory: frontend
