name: dev
on:
  pull_request:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/**"
jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: checkout
        uses: actions/checkout@v1
      - name: install
        run: yarn install --production=false
      - name: install functions deps
        run: yarn install
        working-directory: frontend/functions
      - name: tests
        run: yarn test
      - name: build
        run: yarn build-dev
      - name: deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --dir=build
