name: Fly Deploy
on:
  pull_request:
    branches:
      - master
    # paths-ignore:
    #   - ".github/**"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy backend --dockerfile backend/Dockerfile"
