name: Fly Deploy
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.0
        with:
          args: "deploy"
          working-directory: backend
